project:
  type: website
  output-dir: docs

website:
  site-url: https://acohenstat.github.io/main
  # cookie-consent: 
  #   type: express 
  #   style: headline
  #   palette: dark
  favicon: images/achraf.jpeg
  google-analytics: 
    tracking-id: ""
    anonymize-ip: true
  # title: "achraf cohen"
  navbar:
    title: false
    #logo: images/logos/nunito/creamBG_greenText/logo_nunito_cropped.png
    logo-alt:  'achraf cohen'  
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Research
      - posts.qmd
      - resources.qmd
      # - href: CV/.pdf
      #   text: cv
      - icon: github
        href: https://github.com/acohenstat
      - icon: robot
        href: https://acohenstat.github.io
      # - icon: twitter
      #   href: https://twitter.com/SamanthaCsik
      - icon: linkedin
        href:  https://www.linkedin.com/in/achraf-cohen-94047421/en
      - icon: envelope
        href: mailto:acohen@uwf.edu
  page-footer: 
    background: dark
    left: Copyright 2023, Achraf Cohen
    right: This website is built with [Quarto](https://quarto.org/)
    # right: 
    #   - icon: github
    #     href: https://github.com/samanthacsik
    #   - icon: twitter
    #     href: https://twitter.com/SamanthaCsik
    #   - icon: linkedin
    #     href: https://www.linkedin.com/in/samanthacsik/
    #   - icon: envelope
    #     href: mailto:scsik@ucsb.edu
  # reader-mode: true
  # repo-url: https://github.com/samanthacsik/samanthacsik-quarto-website
  # repo-actions: [edit, issue]

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - green_theme.scss
    # css: styles.css
    mainfont: Nunito
    toc: true


