project:
  type: website
  output-dir: docs

website:
  title: "samantha csik"
  navbar:
    left:
      - href: index.qmd
        text: home
      - about.qmd
      - posts.qmd
      - resources.qmd
  page-footer: 
    background: light
    left: "Copyright 2021, Samantha Csik"
    right: 
      - icon: github
        href: https://github.com/samanthacsik
      - icon: twitter
        href: https://twitter.com/SamanthaCsik
  reader-mode: true
  repo-url: https://github.com/samanthacsik/samanthacsik-quarto-website
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


