project:
  type: website
  output-dir: docs

website:
  title: "samantha csik"
  navbar:
    left:
      - href: index.qmd
        text: home
      - about.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


